/*
 * The Shadow Simulator
 * See LICENSE for licensing information
 */
// clang-format off


#ifndef main_opaque_bindings_h
#define main_opaque_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef enum InterposeMethod {
  // Attach to child using ptrace and use it to interpose syscalls etc.
  INTERPOSE_METHOD_PTRACE,
  // Use LD_PRELOAD to load a library that implements the libC interface which will
  // route syscalls to Shadow.
  INTERPOSE_METHOD_PRELOAD,
  // Use both PRELOAD and PTRACE based interposition.
  INTERPOSE_METHOD_HYBRID,
} InterposeMethod;

typedef enum QDiscMode {
  Q_DISC_MODE_FIFO,
  Q_DISC_MODE_ROUND_ROBIN,
} QDiscMode;

// A queue of byte chunks.
typedef struct ByteQueue ByteQueue;

// Run real applications over simulated networks.
typedef struct CliOptions CliOptions;

typedef struct CompatDescriptor CompatDescriptor;

// Options contained in a configuration file.
typedef struct ConfigFileOptions ConfigFileOptions;

// Shadow configuration options after processing command-line and configuration file options.
typedef struct ConfigOptions ConfigOptions;

// The main counter object that maps individual keys to count values.
typedef struct Counter Counter;

typedef struct HostOptions HostOptions;

// Manages memory of a plugin process.
typedef struct MemoryManager MemoryManager;

// Read-accessor to plugin memory.
typedef struct MemoryReader_u8 MemoryReader_u8;

// Write-accessor to plugin memory.
typedef struct MemoryWriter_u8 MemoryWriter_u8;

// An opaque type used when passing `*const AtomicRefCell<File>` to C.
typedef struct PosixFileArc PosixFileArc;

typedef struct ProcessOptions ProcessOptions;

#endif /* main_opaque_bindings_h */
