/*
 * The Shadow Simulator
 * See LICENSE for licensing information
 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A queue of byte chunks.
typedef struct ByteQueue ByteQueue;

void bytequeue_free(ByteQueue *bq_ptr);

ByteQueue *bytequeue_new(size_t chunk_size);

size_t bytequeue_pop(ByteQueue *bq, unsigned char *dst, size_t len);

void bytequeue_push(ByteQueue *bq, const unsigned char *src, size_t len);
