#ifndef LIB_SHIM_SHIM_SIGNALS_H
#define LIB_SHIM_SHIM_SIGNALS_H

#include <stdbool.h>

#include "lib/shadow-shim-helper-rs/shim_helper.h"

// Install signal handlers for signals that can be generated by hardware errors.
// e.g. SIGSEGV
void shim_install_hardware_error_handlers();

// More-specialized error handlers (e.g. for rdtsc) can invoke this handler
// directly when unable to handle the current signal (e.g. when a SIGSEGV wasn't
// caused by an rdtsc instruction)
void shim_handle_hardware_error_signal(int, siginfo_t*, void*);

#endif