/*
 * scallion_registration.c
 *
 *  Created on: Mar 4, 2011
 *      Author: rob
 */

const char tor_git_revision[] = "";

#include "scallion.h"

#include "tor_includes.h"
#include "tor_externs.h"

void scallion_register_globals(scallion_t* scallion_global_data, scallion_tp* scallion) {
	snri_register_globals(408,
		sizeof(scallion_t), scallion_global_data,
		sizeof(scallion_tp), scallion,

		/* statics */
		sizeof(int), &gzip_is_supported,
		sizeof(char*), &_openssl_mutexes,
		sizeof(int), &_n_openssl_mutexes,
		sizeof(int), &_crypto_global_initialized,
		sizeof(char*), &dh_param_p,
		sizeof(char*), &dh_param_g,
		sizeof(int), &use_unsafe_renegotiation_op,
		sizeof(int), &use_unsafe_renegotiation_flag,
		sizeof(char*), &CLIENT_CIPHER_DUMMIES,
		sizeof(char*), &CLIENT_CIPHER_STACK,
		sizeof(struct tlsmap), &tlsmap_root,
		sizeof(char*), &global_tls_context,
		sizeof(int), &tls_library_is_initialized,
		sizeof(ssl_state_buf), ssl_state_buf,
		sizeof(int), &align,
		sizeof(size_t), &g_alignment,
		sizeof(pthread_mutex_t), &gen_mutex,
		sizeof(unsigned int), &malloc_started,
		sizeof(unsigned int), &malloc_cache,
		sizeof(char*), &last_dir,
		sizeof(char*), &prev_dir,
		sizeof(size_t), &pdi_off,
		sizeof(u_long), &pdi_mod,
		sizeof(u_long), &last_index,
		sizeof(char*), &page_dir,
		sizeof(struct pgfree), &free_list,
		sizeof(int), &malloc_abort,
		sizeof(int), &suicide,
		sizeof(int), &malloc_silent,
		sizeof(int), &malloc_realloc,
		sizeof(int), &malloc_freeprot,
		sizeof(size_t), &malloc_guard,
		sizeof(size_t), &malloc_guarded,
		sizeof(int), &malloc_ptrguard,
		sizeof(int), &malloc_hint,
		sizeof(int), &malloc_xmalloc,
		sizeof(int), &malloc_zero,
		sizeof(int), &malloc_junk,
		sizeof(int), &malloc_utrace,
		sizeof(int), &malloc_active,
		sizeof(size_t), &malloc_used,
		sizeof(caddr_t), &malloc_brk,
		sizeof(char*), &px,
		sizeof(int), &noprint,
		sizeof(int), &freelist_len,
		sizeof(char*), &freelist,
		sizeof(char*), &open_sockets,
		sizeof(int), &max_socket,
		sizeof(int), &n_sockets_open,
		sizeof(char*), &socket_accounting_mutex,
		sizeof(int), &have_already_switched_id,
		sizeof(uname_result), uname_result,
		sizeof(int), &uname_result_is_set,
		sizeof(char*), &t_mut,
		sizeof(char*), &gt_mut,
		sizeof(pthread_mutexattr_t), &attr_reentrant,
		sizeof(int), &threads_initialized,
		sizeof(int), &memory_lock_attempted,
		sizeof(unsigned long), &main_thread_id,
		sizeof(fmt_addr_buf), fmt_addr_buf,
		sizeof(hex_str_buf), hex_str_buf,
		sizeof(char*), &_escaped_val,
		sizeof(time_t), &cached_approx_time,
		sizeof(int), &ftime_skew,
		sizeof(int), &ftime_slop,
		sizeof(int), &start_daemon_called,
		sizeof(int), &finish_daemon_called,
		sizeof(daemon_filedes), daemon_filedes,
		sizeof(tor_mutex_t), &log_mutex,
		sizeof(int), &log_mutex_initialized,
		sizeof(char*), &logfiles,
		sizeof(int), &syslog_count,
		sizeof(char*), &appname,
		sizeof(int), &have_warned_about_unsafe_socks,
		sizeof(int), &num_cpuworkers,
		sizeof(int), &num_cpuworkers_busy,
		sizeof(time_t), &last_rotation_time,
		sizeof(event_mask_t), &global_event_mask,
		sizeof(int), &disable_log_messages,
		sizeof(int), &authentication_cookie_is_set,
		sizeof(authentication_cookie), authentication_cookie,
		sizeof(last_sent_bootstrap_message), last_sent_bootstrap_message,
		sizeof(int), &bootstrap_percent,
		sizeof(int), &bootstrap_problems,
		sizeof(char*), &geoip_countries,
		sizeof(char*), &country_idxplus1_by_lc_code,
		sizeof(char*), &geoip_entries,
		sizeof(struct clientmap), &client_history,
		sizeof(time_t), &last_time_determined_shares,
		sizeof(double), &v2_share_times_seconds,
		sizeof(double), &v3_share_times_seconds,
		sizeof(int), &share_seconds,
		sizeof(ns_v2_responses), ns_v2_responses,
		sizeof(ns_v3_responses), ns_v3_responses,
		sizeof(int), &arrays_initialized,
		sizeof(struct dirreqmap), &dirreq_map,
		sizeof(time_t), &start_of_dirreq_stats_interval,
		sizeof(time_t), &start_of_bridge_stats_interval,
		sizeof(char*), &bridge_stats_extrainfo,
		sizeof(char*), &bridge_stats_controller,
		sizeof(time_t), &start_of_entry_stats_interval,
		sizeof(struct timeval), &cached_time_hires,
		sizeof(int), &num_seen,
		sizeof(uint64_t), &next_id,
		sizeof(int), &total_cells_allocated,
		sizeof(char*), &cell_pool,
		sizeof(char*), &it_pool,
		sizeof(double), &ewma_scale_factor,
		sizeof(int), &ewma_enabled,
		sizeof(char*), &socks_policy,
		sizeof(char*), &dir_policy,
		sizeof(char*), &authdir_reject_policy,
		sizeof(char*), &authdir_invalid_policy,
		sizeof(char*), &authdir_baddir_policy,
		sizeof(char*), &authdir_badexit_policy,
		sizeof(char*), &reachable_or_addr_policy,
		sizeof(char*), &reachable_dir_addr_policy,
		sizeof(struct policy_map), &policy_root,
		sizeof(voting_schedule_t), &voting_schedule,
		sizeof(char*), &pending_vote_list,
		sizeof(char*), &previous_vote_list,
		sizeof(pending_consensuses), pending_consensuses,
		sizeof(char*), &pending_consensus_signatures,
		sizeof(char*), &pending_consensus_signature_list,
		sizeof(char*), &microdesc_consensus_methods,
		sizeof(int), &stats_prev_global_read_bucket,
		sizeof(int), &stats_prev_global_write_bucket,
		sizeof(uint64_t), &stats_n_bytes_read,
		sizeof(uint64_t), &stats_n_bytes_written,
		sizeof(time_t), &time_to_check_for_correct_dns,
		sizeof(time_t), &time_of_last_signewnym,
		sizeof(int), &signewnym_is_pending,
		sizeof(char*), &connection_array,
		sizeof(char*), &closeable_connection_lst,
		sizeof(char*), &active_linked_connection_lst,
		sizeof(int), &called_loop_once,
		sizeof(time_t), &last_rotated_x509_certificate,
		sizeof(time_t), &time_to_check_v3_certificate,
		sizeof(time_t), &time_to_check_listeners,
		sizeof(time_t), &time_to_check_descriptor,
		sizeof(time_t), &time_to_check_ipaddress,
		sizeof(time_t), &time_to_shrink_memory,
		sizeof(time_t), &time_to_try_getting_descriptors,
		sizeof(time_t), &time_to_reset_descriptor_failures,
		sizeof(time_t), &time_to_add_entropy,
		sizeof(time_t), &time_to_write_bridge_status_file,
		sizeof(time_t), &time_to_downrate_stability,
		sizeof(time_t), &time_to_save_stability,
		sizeof(time_t), &time_to_clean_caches,
		sizeof(time_t), &time_to_recheck_bandwidth,
		sizeof(time_t), &time_to_check_for_expired_networkstatus,
		sizeof(time_t), &time_to_write_stats_files,
		sizeof(time_t), &time_to_write_bridge_stats,
		sizeof(int), &should_init_bridge_stats,
		sizeof(time_t), &time_to_retry_dns_init,
		sizeof(int), &dirport_reachability_count,
		sizeof(char*), &second_timer,
		sizeof(int), &n_libevent_errors,
		sizeof(time_t), &cur_sec_elap,
		sizeof(char*), &signal_events[16],
		sizeof(char*), &lockfile,
		sizeof(char*), &entry_guards,
		sizeof(int), &entry_guards_dirty,
		sizeof(int), &unit_tests,
		sizeof(int), &should_add_entry_nodes,
		sizeof(char*), &bridge_list,
		sizeof(char*), &rend_service_list,
		sizeof(int), &consider_republishing_rend_descriptors,
		sizeof(struct timeval), &exit_now,
		sizeof(char*), &circuits_pending_or_conns,
		sizeof(struct orconn_circid_map), &orconn_circid_circuit_map,
		sizeof(circ_state_buf), circ_state_buf,
		sizeof(circ_purp_buf), circ_purp_buf,
		sizeof(uint32_t), &n_circuits_allocated,
		sizeof(char*), &rend_cache,
		sizeof(char*), &rend_cache_v2_dir,
		sizeof(uint32_t), &last_interface_ip,
		sizeof(char*), &outgoing_addrs,
		sizeof(conn_type_buf), conn_type_buf,
		sizeof(conn_st_buf), conn_st_buf,
		sizeof(uint64_t), &n_connections_allocated,
		sizeof(time_t), &last_conn_warning,
		sizeof(int), &write_buckets_empty_last_second,
		sizeof(hibernate_state_t), &hibernate_state,
		sizeof(time_t), &hibernate_end_time,
		sizeof(time_t), &shutdown_time,
		sizeof(uint64_t), &n_bytes_read_in_interval,
		sizeof(uint64_t), &n_bytes_written_in_interval,
		sizeof(uint32_t), &n_seconds_active_in_interval,
		sizeof(time_t), &interval_start_time,
		sizeof(time_t), &interval_end_time,
		sizeof(time_t), &interval_wakeup_time,
		sizeof(uint64_t), &expected_bandwidth_usage,
		sizeof(time_unit_t), &cfg_unit,
		sizeof(int), &cfg_start_day,
		sizeof(int), &cfg_start_hour,
		sizeof(int), &cfg_start_min,
		sizeof(uint64_t), &last_read_bytes_noted,
		sizeof(uint64_t), &last_written_bytes_noted,
		sizeof(time_t), &last_time_noted,
		sizeof(char*), &the_evdns_base,
		sizeof(int), &nameservers_configured,
		sizeof(int), &nameserver_config_failed,
		sizeof(char*), &resolv_conf_fname,
		sizeof(time_t), &resolv_conf_mtime,
		sizeof(struct cache_map), &cache_root,
		sizeof(int), &all_down,
		sizeof(char*), &cached_resolve_pqueue,
		sizeof(int), &n_wildcard_requests,
		sizeof(char*), &dns_wildcard_response_count,
		sizeof(char*), &dns_wildcard_list,
		sizeof(int), &dns_wildcard_one_notice_given,
		sizeof(int), &dns_wildcard_notice_given,
		sizeof(char*), &dns_wildcarded_test_address_list,
		sizeof(int), &dns_wildcarded_test_address_notice_given,
		sizeof(int), &dns_is_completely_invalid,
		sizeof(char*), &launch_event,
		sizeof(char*), &addressmap,
		sizeof(char*), &virtaddress_reversemap,
		sizeof(uint32_t), &virtual_addr_network,
		sizeof(maskbits_t), &virtual_addr_netmask_bits,
		sizeof(uint32_t), &next_virtual_addr,
		sizeof(int), &pf_socket,
		sizeof(routerdesc_token_table), routerdesc_token_table,
		sizeof(extrainfo_token_table), extrainfo_token_table,
		sizeof(rtrstatus_token_table), rtrstatus_token_table,
		sizeof(netstatus_token_table), netstatus_token_table,
		sizeof(dir_footer_token_table), dir_footer_token_table,
		sizeof(dir_token_table), dir_token_table,
		sizeof(dir_key_certificate_table), dir_key_certificate_table,
		sizeof(desc_token_table), desc_token_table,
		sizeof(ipo_token_table), ipo_token_table,
		sizeof(client_keys_token_table), client_keys_token_table,
		sizeof(networkstatus_token_table), networkstatus_token_table,
		sizeof(networkstatus_consensus_token_table), networkstatus_consensus_token_table,
		sizeof(networkstatus_vote_footer_token_table), networkstatus_vote_footer_token_table,
		sizeof(networkstatus_detached_signature_token_table), networkstatus_detached_signature_token_table,
		sizeof(microdesc_token_table), microdesc_token_table,
		sizeof(time_t), &last_desc_dumped,
		sizeof(char*), &verified_digests,
		sizeof(time_t), &stability_last_downrated,
		sizeof(time_t), &started_tracking_stability,
		sizeof(char*), &history_map,
		sizeof(char*), &last_stability_doc,
		sizeof(time_t), &built_last_stability_doc_at,
		sizeof(int), &n_bogus_times,
		sizeof(char*), &read_array,
		sizeof(char*), &write_array,
		sizeof(char*), &dir_read_array,
		sizeof(char*), &dir_write_array,
		sizeof(char*), &predicted_ports_list,
		sizeof(char*), &predicted_ports_times,
		sizeof(time_t), &predicted_internal_time,
		sizeof(time_t), &predicted_internal_uptime_time,
		sizeof(time_t), &predicted_internal_capacity_time,
		sizeof(pk_op_counts_t), &pk_op_counts,
		sizeof(char*), &exit_bytes_read,
		sizeof(char*), &exit_bytes_written,
		sizeof(char*), &exit_streams,
		sizeof(time_t), &start_of_exit_stats_interval,
		sizeof(time_t), &start_of_buffer_stats_interval,
		sizeof(char*), &trusted_dir_servers,
		sizeof(char*), &trusted_dir_certs,
		sizeof(int), &trusted_dir_servers_certs_changed,
		sizeof(char*), &routerlist,
		sizeof(char*), &warned_nicknames,
		sizeof(time_t), &last_routerdesc_download_attempted,
		sizeof(uint64_t), &sl_last_total_weighted_bw,
		sizeof(uint64_t), &sl_last_weighted_bw_of_me,
		sizeof(time_t), &last_dummy_download,
		sizeof(int), &have_min_dir_info,
		sizeof(int), &need_to_update_have_min_dir_info,
		sizeof(dir_info_status), dir_info_status,
		sizeof(char*), &info,
		sizeof(int), &num_create,
		sizeof(int), &create_time,
		sizeof(time_t), &curr_sec,
		sizeof(int), &num_versions,
		sizeof(_option_abbrevs), _option_abbrevs,
		sizeof(_state_abbrevs), _state_abbrevs,
		sizeof(_option_vars), _option_vars,
		sizeof(testing_tor_network_defaults), testing_tor_network_defaults,
		sizeof(_state_vars), _state_vars,
		sizeof(config_format_t), &options_format,
		sizeof(config_var_t), &state_extra_var,
		sizeof(config_format_t), &state_format,
		sizeof(char*), &global_options,
		sizeof(char*), &torrc_fname,
		sizeof(char*), &global_state,
		sizeof(char*), &global_cmdline_options,
		sizeof(char*), &global_dirfrontpagecontents,
		sizeof(char*), &_version,
		sizeof(int), &libevent_initialized,
		sizeof(uint32_t), &last_resolved_addr,
		sizeof(char*), &backup_argv,
		sizeof(int), &backup_argc,
		sizeof(memory_units), memory_units,
		sizeof(time_units), time_units,
		sizeof(char*), &v2_download_status_map,
		sizeof(char*), &networkstatus_v2_list,
		sizeof(int), &networkstatus_v2_list_has_changed,
		sizeof(char*), &named_server_map,
		sizeof(char*), &unnamed_server_map,
		sizeof(char*), &current_consensus,
		sizeof(consensus_waiting_for_certs), consensus_waiting_for_certs,
		sizeof(time_t), &last_networkstatus_download_attempted,
		sizeof(time_t), &time_to_download_next_consensus,
		sizeof(consensus_dl_status), consensus_dl_status,
		sizeof(int), &have_warned_about_old_version,
		sizeof(int), &have_warned_about_new_version,
		sizeof(char*), &orconn_identity_map,
		sizeof(char*), &ol_list,
		sizeof(char*), &ol_tail,
		sizeof(int), &ol_length,
		sizeof(time_t), &last_circ_warning,
		sizeof(time_t), &time_to_new_circuit,
		sizeof(int), &have_performed_bandwidth_test,
		sizeof(int), &n_circuit_failures,
		sizeof(int), &did_circs_fail_last_period,
		sizeof(char*), &key_lock,
		sizeof(time_t), &onionkey_set_at,
		sizeof(char*), &onionkey,
		sizeof(char*), &lastonionkey,
		sizeof(char*), &identitykey,
		sizeof(identitykey_digest), identitykey_digest,
		sizeof(char*), &authority_signing_key,
		sizeof(char*), &authority_key_certificate,
		sizeof(char*), &legacy_signing_key,
		sizeof(char*), &legacy_key_certificate,
		sizeof(time_t), &last_exp_warning,
		sizeof(int), &can_reach_or_port,
		sizeof(int), &can_reach_dir_port,
		sizeof(int), &advertising,
		sizeof(int), &server_is_advertised,
		sizeof(char*), &desc_routerinfo,
		sizeof(char*), &desc_extrainfo,
		sizeof(time_t), &desc_clean_since,
		sizeof(int), &desc_needs_upload,
		sizeof(char*), &warned_nonexistent_family,
		sizeof(time_t), &last_changed,
		sizeof(uint32_t), &last_guessed_ip,
		sizeof(int), &write_stats_to_extrainfo,
		sizeof(char*), &last_hid_serv_requests,
		sizeof(char*), &auth_hid_servs,
		sizeof(char*), &request_map,
		sizeof(char*), &the_microdesc_cache,
		sizeof(time_t), &the_directory_is_dirty,
		sizeof(time_t), &runningrouters_is_dirty,
		sizeof(time_t), &the_v2_networkstatus_is_dirty,
		sizeof(char*), &the_directory,
		sizeof(cached_dir_t), &the_runningrouters,
		sizeof(char*), &fingerprint_list,
		sizeof(char*), &cached_directory,
		sizeof(cached_dir_t), &cached_runningrouters,
		sizeof(char*), &cached_v2_networkstatus,
		sizeof(char*), &cached_consensuses,
		sizeof(char*), &the_v2_networkstatus,
		sizeof(uint32_t), &stable_uptime,
		sizeof(double), &stable_mtbf,
		sizeof(int), &enough_mtbf_info,
		sizeof(double), &guard_wfu,
		sizeof(long), &guard_tk,
		sizeof(uint32_t), &fast_bandwidth,
		sizeof(uint32_t), &guard_bandwidth_including_exits,
		sizeof(uint32_t), &guard_bandwidth_excluding_exits,
		sizeof(uint64_t), &total_bandwidth,
		sizeof(uint64_t), &total_exit_bandwidth,
		sizeof(char), &ctr,

		/* globals */
		sizeof(int), &global_read_bucket,
		sizeof(int), &global_write_bucket,
		sizeof(int), &created_time,
		sizeof(int), &destroy_time,
		sizeof(freelists), &freelists,
		sizeof(uint64_t), &n_freelist_miss,
		sizeof(int), &num_cert,
		sizeof(int), &num_created,
		sizeof(int), &num_destroy,
		sizeof(int), &num_relay,
		sizeof(int), &relay_time,
		sizeof(circuit_build_times_t), &circ_times,
		sizeof(char*), &_last_circid_orconn_ent,
		sizeof(char*), &global_circuitlist,
		/* sizeof(orconn_circid_map_N_PRIMES), &orconn_circid_map_N_PRIMES, // constant */
		/* sizeof(orconn_circid_map_PRIMES), &orconn_circid_map_PRIMES, // constant */
		sizeof(uint64_t), &stats_n_create_cells_processed,
		sizeof(uint64_t), &stats_n_created_cells_processed,
		sizeof(uint64_t), &stats_n_destroy_cells_processed,
		sizeof(uint64_t), &stats_n_netinfo_cells_processed,
		sizeof(uint64_t), &stats_n_padding_cells_processed,
		sizeof(uint64_t), &stats_n_relay_cells_processed,
		sizeof(uint64_t), &stats_n_versions_cells_processed,
		/* sizeof(n_or_protocol_versions), &n_or_protocol_versions, // constant */
		/* sizeof(or_protocol_versions), &or_protocol_versions, // constant */
		/* sizeof(CSWTCH.420), &CSWTCH.420, // unknown */
		/* sizeof(CSWTCH.423), &CSWTCH.423, // unknown */
		/* sizeof(getinfo_items), &getinfo_items, // constant */
		/* sizeof(bridge_dl_schedule), &bridge_dl_schedule, // constant */
		/* sizeof(client_consensus_dl_schedule), &client_consensus_dl_schedule, // constant */
		/* sizeof(client_dl_schedule), &client_dl_schedule, // constant */
		/* sizeof(server_consensus_dl_schedule), &server_consensus_dl_schedule, // constant */
		/* sizeof(server_dl_schedule), &server_dl_schedule, // constant */
		/* sizeof(cache_map_N_PRIMES), &cache_map_N_PRIMES, // constant */
		/* sizeof(cache_map_PRIMES), &cache_map_PRIMES, // constant */
		/* sizeof(clientmap_N_PRIMES), &clientmap_N_PRIMES, // constant */
		/* sizeof(clientmap_PRIMES), &clientmap_PRIMES, // constant */
		/* sizeof(dirreqmap_N_PRIMES), &dirreqmap_N_PRIMES, // constant */
		/* sizeof(dirreqmap_PRIMES), &dirreqmap_PRIMES, // constant */
		sizeof(int), &global_relayed_read_bucket,
		sizeof(int), &global_relayed_write_bucket,
		sizeof(int), &has_completed_circuit,
		sizeof(long), &stats_n_seconds_working,
		sizeof(time_t), &time_of_process_start,
		/* sizeof(microdesc_map_N_PRIMES), &microdesc_map_N_PRIMES, // constant */
		/* sizeof(microdesc_map_PRIMES), &microdesc_map_PRIMES, // constant */
		/* sizeof(policy_map_N_PRIMES), &policy_map_N_PRIMES, // constant */
		/* sizeof(policy_map_PRIMES), &policy_map_PRIMES, // constant */
		/* sizeof(private_nets), &private_nets, // constant */
		/* sizeof(CSWTCH.49), &CSWTCH.49, // unknown */
		sizeof(uint64_t), &stats_n_data_bytes_packaged,
		sizeof(uint64_t), &stats_n_data_bytes_received,
		sizeof(uint64_t), &stats_n_data_cells_packaged,
		sizeof(uint64_t), &stats_n_data_cells_received,
		sizeof(uint64_t), &stats_n_relay_cells_delivered,
		sizeof(uint64_t), &stats_n_relay_cells_relayed,
		sizeof(char*), &circuits_for_buffer_stats,
		sizeof(uint64_t), &rephist_total_alloc,
		sizeof(uint32_t), &rephist_total_num,
		/* sizeof(global_nameserver_timeouts), &global_nameserver_timeouts, // constant */
		/* sizeof(global_nameserver_timeouts_length), &global_nameserver_timeouts_length, // constant */
		sizeof(int), &_log_global_min_severity,
		/* sizeof(domain_list), &domain_list, // constant */
		/* sizeof(CSWTCH.220), &CSWTCH.220, // unknown */
		/* sizeof(MONTH_NAMES), &MONTH_NAMES, // constant */
		/* sizeof(WEEKDAY_NAMES), &WEEKDAY_NAMES, // constant */
		/* sizeof(days_per_month), &days_per_month, // constant */
		/* sizeof(TOR_ISALNUM_TABLE), &TOR_ISALNUM_TABLE, // constant */
		/* sizeof(TOR_ISALPHA_TABLE), &TOR_ISALPHA_TABLE, // constant */
		/* sizeof(TOR_ISDIGIT_TABLE), &TOR_ISDIGIT_TABLE, // constant */
		/* sizeof(TOR_ISLOWER_TABLE), &TOR_ISLOWER_TABLE, // constant */
		/* sizeof(TOR_ISPRINT_TABLE), &TOR_ISPRINT_TABLE, // constant */
		/* sizeof(TOR_ISSPACE_TABLE), &TOR_ISSPACE_TABLE, // constant */
		/* sizeof(TOR_ISUPPER_TABLE), &TOR_ISUPPER_TABLE, // constant */
		/* sizeof(TOR_ISXDIGIT_TABLE), &TOR_ISXDIGIT_TABLE, // constant */
		/* sizeof(TOR_TOLOWER_TABLE), &TOR_TOLOWER_TABLE, // constant */
		/* sizeof(TOR_TOUPPER_TABLE), &TOR_TOUPPER_TABLE, // constant */
		/* sizeof(digestmap_impl_N_PRIMES), &digestmap_impl_N_PRIMES, // constant */
		/* sizeof(digestmap_impl_PRIMES), &digestmap_impl_PRIMES, // constant */
		/* sizeof(strmap_impl_N_PRIMES), &strmap_impl_N_PRIMES, // constant */
		/* sizeof(strmap_impl_PRIMES), &strmap_impl_PRIMES, // constant */
		/* sizeof(base64_decode_table), &base64_decode_table, // constant */
		/* sizeof(CLIENT_CIPHER_INFO_LIST), &CLIENT_CIPHER_INFO_LIST, // constant */
		/* sizeof(CLIENT_CIPHER_LIST), &CLIENT_CIPHER_LIST, // constant */
		/* sizeof(CSWTCH.177), &CSWTCH.177, // unknown */
		/* sizeof(N_CLIENT_CIPHERS), &N_CLIENT_CIPHERS, // constant */
		/* sizeof(state_map), &state_map, // constant */
		/* sizeof(tlsmap_N_PRIMES), &tlsmap_N_PRIMES, // constant */
		/* sizeof(tlsmap_PRIMES), &tlsmap_PRIMES, // constant */
		/* sizeof(suppress_msg), &suppress_msg, // constant */
		sizeof(char*), &the_event_base,

		sizeof(errno), &errno
		);
}
