#!/usr/bin/env python2.7

import sys, os, argparse, subprocess
from datetime import datetime

# path to the built-in example plug-ins DSIM files relative to the shadow base directory
ECHO_PATH="share/shadow"
PINGPONG_PATH="share/shadow"
FILETRANSFER_PATH="share/shadow"

# path to the preload lib relative to the cmake dir
PRELOAD_PATH="lib/libshadow-preload.so"

# path to the shadow binary relative to the cmake dir
SHADOW_PATH="bin/shadow-bin"

# path to other programs
TIME_PATH="/usr/bin/time"
VALGRIND_PATH="/usr/bin/valgrind"

def main():
    parser_main = argparse.ArgumentParser(description='Utility to help run the shadow simulator', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_main.add_argument('-q', '--quiet', action="store_true", dest="be_quiet",
          help="this script will not display its actions", default=False)
    
    # @todo: refactor - many of the arguments are shared among subparsers
    # setup our commands
    subparsers_main = parser_main.add_subparsers(help='run a subcommand (for help use <subcommand> --help)')
    
    # run subcommand
    parser_run = subparsers_main.add_parser('run', help='run the shadow simulator', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_run.set_defaults(func=run, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    
    # run options
    parser_run.add_argument('-c', '--config', action="store", dest="config_file",
          help="path to custom shadow configuration options")
    parser_run.add_argument('-d', '--dsim', action="store", dest="dsim_file",
          help="path to custom simulation description (dsim) script", required=True)
    parser_run.add_argument('-p', '--processes', type=int, action="store", dest="num_processes", choices=[1,2,3,4,5,6,7,8,9,10,11,12],
          help="number of worker processes, in addition to the master process, to use in the simulation", default=1)
    parser_run.add_argument('-l', '--ld-preload', action="append", dest="extra_preloads",
          help="add a library to the list of libraries that will be preloaded before running shadow")
    parser_run.add_argument('-g', '--valgrind', action="store_true", dest="use_valgrind",
          help="run under the valgrind memory checker", default=False)
    parser_run.add_argument('--dry-run', action="store_true", dest="do_dry_run",
          help="do everything except invoking shadow", default=False)
        
    # autorun command
    parser_autorun = subparsers_main.add_parser('auto', help='run the shadow simulator using default plug-ins and dsim files', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_autorun.set_defaults(func=auto, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    
    # autorun options
    parser_autorun.add_argument('-p', '--processes', type=int, action="store", metavar="N", dest="num_processes", choices=[1,2,3,4,5,6,7,8,9,10,11,12],
          help="number of worker processes, in addition to the master process, to use in the simulation", default=1)
    
    # default built-in examples
    group_autorun = parser_autorun.add_mutually_exclusive_group(required=True)
    group_autorun.add_argument('--echo-eth', action="store_true", dest="run_echo_eth", 
          help="run the echo example with a client and server over ethernet", default=False)
    group_autorun.add_argument('--echo-lo', action="store_true", dest="run_echo_loop", 
          help="run the echo example with a client and server over loopback", default=False)
    group_autorun.add_argument('--pingpong-tcp', action="store_true", dest="run_pingpong_tcp", 
          help="run the ping-pong example using tcp", default=False)
    group_autorun.add_argument('--pingpong-udp', action="store_true", dest="run_pingpong_udp", 
          help="run the ping-pong example using udp", default=False)
    group_autorun.add_argument('--filetransfer', action="store_true", dest="run_filetransfer", 
          help="run filetransfer example with clients and a server over ethernet", default=False)
    
    # get arguments, accessible with args.value
    args = parser_main.parse_args()
    # run chosen command
    args.func(args)

def run(args):
    filepath=os.path.abspath(__file__)
    args.shadow_directory = os.path.abspath(filepath[:filepath.rfind("/")] + "/../")
    
    # start with the default preload
    preloads = os.path.abspath(args.shadow_directory + '/' + PRELOAD_PATH)
    # add user-specified preloads
    if args.extra_preloads is not None:
        for user_preload in args.extra_preloads:
            preloads += ":" + os.path.abspath(user_preload.strip())
    
    os.putenv("LD_PRELOAD", preloads)
    log(args, "set environmental variable: LD_PRELOAD=" + preloads)
    
    dsim = os.path.abspath(args.dsim_file)
    log(args, "using dsim: " + dsim)
    
    rundir = os.getcwd()
    os.chdir(args.shadow_directory)
    
    shadow = os.path.abspath(args.shadow_directory + "/" + SHADOW_PATH)
    
    # use default built-in config by not specifying a "-c" option, unless they passed a config file
    shadow_args = [shadow, "-p", str(args.num_processes), "-d", dsim]
    if(args.config_file is not None):
        shadow_args.append("-c")
        shadow_args.append(os.path.abspath(args.config_file))
    
    # prepending with either time or valgrind
    run_args = None
    if(args.use_valgrind):
        run_args = [VALGRIND_PATH, "--leak-check=full", "--show-reachable=yes", "--track-origins=yes", "--trace-children=yes", "--log-file=valgrind-shadow-%p.log", "--error-limit=no"]
        log(args, "logging valgrind output to logfile")
    else: 
        run_args = [TIME_PATH]
        
    run_args.extend(shadow_args)
    log_list(args, "running shadow from\n\t" + args.shadow_directory + "\nusing args\n\t", run_args)
    
    if(not args.do_dry_run):
        retcode = subprocess.call(run_args, stdout=get_outfile(args))
        log_result(args, "run", retcode)
    
    os.chdir(rundir)
 
def auto(args):
    filepath=os.path.abspath(__file__)
    installdir = os.path.abspath(filepath[:filepath.rfind("/")] + "/../")
    
    # default preloads depend what we are running
    preloads = installdir + '/' + PRELOAD_PATH
    dsim_path = ""

    if(args.run_echo_eth):
        dsim_path = os.path.abspath(installdir + "/" + ECHO_PATH + "/echo-ethernet.dsim")
    elif(args.run_echo_loop):
        dsim_path = os.path.abspath(installdir + "/" + ECHO_PATH + "/echo-loopback.dsim")
    elif(args.run_pingpong_tcp):
        dsim_path = os.path.abspath(installdir + "/" + PINGPONG_PATH + "/pingpong-tcp.dsim")
    elif(args.run_pingpong_udp):
        dsim_path = os.path.abspath(installdir + "/" + PINGPONG_PATH + "/pingpong-udp.dsim")
    elif(args.run_filetransfer):
        dsim_path = os.path.abspath(installdir + "/" + FILETRANSFER_PATH + "/filetransfer.dsim")
        
    os.putenv("LD_PRELOAD", preloads)
    log(args, "set environmental variable: LD_PRELOAD=" + preloads)
        
    rundir = os.getcwd()
    os.chdir(installdir)
    
    shadow = os.path.abspath(installdir + "/" + SHADOW_PATH)
    
    # use default built-in config by not specifying a "-c" option
    run_args = [TIME_PATH, shadow, "-p", str(args.num_processes), "-d", dsim_path]
    log_list(args, "running shadow from\n\t" + installdir + "\nusing args\n\t", run_args)
    
    retcode = subprocess.call(run_args, stdout=get_outfile(args))
    log_result(args, "autorun", retcode)
    
    os.chdir(rundir)
    
def get_outfile(args):
    # check if we redirect to null
    if(args.be_quiet): return open("/dev/null", 'w')
    else: return None
    
def log(args, msg):
    log_helper(args, msg, "\033[94m")
    
def log_result(args, msg, retcode):
    if(retcode == 0): log_success(args, msg)
    else: log_fail(args, msg)

def log_success(args, msg):
    log_helper(args, msg + ": SUCCEEDED!", "\033[92m")
    
def log_fail(args, msg):
    log_helper(args, msg + ": FAILED!", "\033[91m")
    
def log_helper(args, msg, color_start_code):
    if(not args.be_quiet):
        prefix = "[" + str(datetime.now()) + "] shadow.py: "
        print >> sys.stderr, color_start_code + prefix + msg + "\033[0m"
        
def log_list(args, msg, list):
    for item in list: msg += item + " "
    log(args, msg)

if __name__ == '__main__':
    main()
