#!/usr/bin/env python

'''
/*
 * The Shadow Simulator
 * Copyright (c) 2010-2011, Rob Jansen
 * See LICENSE for licensing information
 */
'''

import sys, os, subprocess
from datetime import datetime

# path to the preload lib - when installed, we should be able to find it here
PRELOAD_PATH=os.path.abspath(os.path.dirname(__file__) + "/../lib/libshadow-preload.so")
# path to valgrind
VALGRIND_PATH="/usr/bin/valgrind"

def main():
    log("Use 'shadow --usage' to get help for the Shadow wrapper script")
    
    preloads = [PRELOAD_PATH]
    valgrind = False
    aesni = False
    shadowArgs = [os.path.dirname(__file__) + "/shadow-bin"]
    
    # parse the arguments
    for i in xrange(1, len(sys.argv)):
        arg = sys.argv[i]
        if arg.find("--valgrind") > -1: valgrind = True
        elif arg.find("--enable-aesni") > -1: aesni = True
        elif arg.find("--preload=") > -1: preloads.append(os.path.abspath(os.path.expanduser(arg[arg.index("--preload=")+10:])))
        elif arg.find("--usage") > -1:
            help()
            exit()
        else: shadowArgs.append(arg)
        
    # make sure the preload library files exist
    for p in preloads:
        if not os.path.exists(p): 
            log("Error! Path does not exist: " + p)
            exit(-1)
    
    # set LD_PRELOAD environment
    ld_preload = ':'.join(preloads)
    os.putenv("LD_PRELOAD", ld_preload)
    log("set environmental variable: LD_PRELOAD=" + ld_preload)
    
    if not aesni:
        os.putenv("OPENSSL_ia32cap", "~0x200000200000000")
        log("set environmental variable: OPENSSL_ia32cap=~0x200000200000000")
    
    command = ' '.join(shadowArgs)
    if(valgrind): 
        # make GLib avoid things that confuse valgrind
        os.putenv("G_DEBUG", "gc-friendly")
        log("set environmental variable: G_DEBUG=gc-friendly")
        os.putenv("G_SLICE", "always-malloc")
        log("set environmental variable: G_SLICE=always-malloc")
        
        ## The following can be used to add internal GLib memory validation that
        ## will abort the program if it finds an error. This is useful outside
        ## of the valgrind context, so that valgrind doesn't complain about
        ## the implementation of the GLib validator. 
        ## e.g. $ G_SLICE=debug-blocks shadow --echo
        #os.putenv("G_SLICE", "debug-blocks")
        #log("set environmental variable: G_SLICE=debug-blocks")
        
        command = VALGRIND_PATH + " --leak-check=full --show-reachable=yes --track-origins=yes --trace-children=yes --log-file=valgrind-shadow-%p.log --error-limit=no " + command
        
    log("running: '" + command + "'")
    retcode = subprocess.call(command.strip().split())
    log("run returned " + str(retcode))
    return retcode
    
def help():
    usage = "shadow [--preload=LIBRARY] [--valgrind] [--enable-aesni] ..."
    
    help = "Utility to help run the shadow simulator by handling LD_PRELOADs\nand passing remaining options to shadow-bin"
    usageHelp = "  --usage\n\tprint this help and exit"
    preloadHelp = "  --preload=LIBRARY\n\tadd a library to the list of libraries that will be preloaded when running shadow-bin\n\t(default=[" + PRELOAD_PATH + "])"
    valgrindHelp = "  --valgrind\n\trun shadow-bin under the valgrind memory checker\n\t(default=False)"
    aesniHelp = "  --enable-aesni\n\tenable AES-NI cipher functions in OpenSSL\n\t(default=False)"
   
    print usage
    print ""
    print help
    print ""
    print usageHelp
    print preloadHelp
    print valgrindHelp
    
def log(msg):
    color_start_code = "\033[94m" # red: \033[91m"
    color_end_code = "\033[0m"
    prefix = "[" + str(datetime.now()) + "] shadow-wrapper: "
    print >> sys.stderr, color_start_code + prefix + msg + color_end_code

if __name__ == '__main__':
    sys.exit(main())
