/*
 * The Shadow Simulator
 * See LICENSE for licensing information
 */
// clang-format off


#ifndef objgraph_bindings_h
#define objgraph_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Root of an "object graph". It holds a lock over the contents of the graph,
// and ensures tracks which tags are locked by the current thread.
//
// We only support a thread having one Root of any given type T being locked at
// once. Crate users should use a private type T that they own to avoid
// conflicts.
typedef struct Root Root;

// Wrapper around a MutexGuard that sets and clears a tag.
typedef struct RootGuard RootGuard;

struct Root *root_new(void);

void root_free(struct Root *root);

struct RootGuard *root_lock(const struct Root *root);

void rootguard_free(struct RootGuard *guard);

#endif /* objgraph_bindings_h */
