# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build Docker
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    # use the oldest kernel supported by github's CI (make sure to update the
    # minimum supported kernel version in documentation when changing)
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        # Run on PR head instead of merge result. Running on the merge
        # result can give confusing results, and we require PR to be up to
        # date with target branch before merging, anyway.
        # See https://github.com/shadow/shadow/issues/2166
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        docker build . -t shadow --shm-size="1g"
        docker run --shm-size="1g" --privileged --rm --entrypoint /src/ci/container_scripts/test.sh shadow
