# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Git Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # Fixup commits are OK in pull requests, but should generally be squashed
  # before merging to master, e.g. using `git rebase -i --autosquash master`.
  # See https://github.com/marketplace/actions/block-autosquash-commits
  block-fixup:
    runs-on: ubuntu-latest

    steps:
        - name: Block autosquash commits
          uses: xt0rted/block-autosquash-commits-action@3c9ba6760eba3c160eead6ed4b6449024ec406ad
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
