# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: PythonLint

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install flake8
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
