# Automatically add and check metadata on pull requests
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Pull Request Metadata"

on:
  pull_request_target:
    # We probably want [opened, synchronize, milestoned] here, but the 'milestoned'
    # event trigger is not yet available on pull requests so we use best effort.
    types: [opened, synchronize, reopened, assigned, edited, ready_for_review]

permissions:
  pull-requests: write

jobs:
  Triage:
    runs-on: ubuntu-latest
    steps:
    - name: Assign Author
      # Add the author as an assignee of the PR
      # https://github.com/marketplace/actions/auto-author-assign
      # before updating the version of this untrusted action, check the code manually
      uses: toshimaru/auto-author-assign@084de2241839f0a3433adfd18d2906e8e786380e
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Apply Labels
      # Add labels based on paths modified in PR
      # https://github.com/actions/labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/pr_labeler_conf.yml
        sync-labels: true
    - name: Check Milestone
      # Check if a pull request is assigned a milestone
      # https://github.com/siimon/milestone-check-action
      # before updating the version of this untrusted action, check the code manually
      uses: siimon/milestone-check-action@5ff17a53248d7aaa65b817458ee6106247625790
